name: Daily Report Reminder (GMT+7 09:30)

on:
  schedule:
    # At 02:15 UTC (09:15 GMT+7) every weekday (Monday to Friday)
    - cron: '15 2 * * 1-5'
  workflow_dispatch: # allows manual run from Actions UI

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send reminder to Google Chat webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          FILE_URL: ${{ secrets.FILE_URL }}
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "ERROR: WEBHOOK_URL not set"
            exit 1
          fi
          MESSAGE="Dear team, please update your daily report on this file ${FILE_URL}"
          echo "Sending reminder: $MESSAGE"
          curl -sS -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{\"text\": $(jq -R -s <<< \"$MESSAGE\") }"
