name: Daily Report Reminder (GMT+7 09:30)

on:
  schedule:
    # Run at 08:30 UTC ≈ 09:30 GMT+7
    - cron: '30 1 * * 1-5'
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Log current UTC and local time
        run: |
          echo "UTC time: $(date -u)"
          echo "Local time (GMT+7): $(TZ='Asia/Bangkok' date)"

      - name: Send reminder to Google Chat webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          FILE_URL: ${{ secrets.FILE_URL }}
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "ERROR: WEBHOOK_URL not set"
            exit 1
          fi
          MESSAGE="Dear team, please update your daily report on this file ${FILE_URL}"
          echo "Sending reminder: $MESSAGE"
          curl -sS -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{\"text\": $(jq -R -s <<< \"$MESSAGE\") }"
